<Project>
  <PropertyGroup>
    <Version>1.0.0</Version>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
    <Product>Dotnet Standalone DevManager</Product>
    <Company>JackBerck</Company>
    <Authors>JackBerck and contributors</Authors>
    <RepositoryUrl>https://github.com/JackBerck/dotnet</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
  </PropertyGroup>
</Project>
